name: delta_chat_core
description: The Delta Chat core plugin provides a wrapper for the Delta Chat Core https://github.com/deltachat/deltachat-core to enable imap / smtp based chats. 
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.3+2

flutter:
  plugin:
    androidPackage: com.openxchange.deltachatcore
    pluginClass: DeltaChatCorePlugin
